# Docker-Compose-Datei für Watchtower (https://hub.docker.com/r/containrrr/watchtower)
services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.40
    restart: unless-stopped


